# Generated by Django 5.1.4 on 2024-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('role', models.CharField(choices=[('client', 'مراجع'), ('therapist', 'مشاور'), ('center', 'مرکز'), ('owner', 'ادمین اصلی')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
