# Generated by Django 5.1.4 on 2024-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_fullname_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='value',
            field=models.TextField(),
        ),
    ]
