# Generated by Django 5.1.4 on 2024-12-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_onetimepassword_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
