# Generated by Django 5.1.4 on 2024-12-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_last_login_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
